require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArtistsController do

  # This should return the minimal set of attributes required to create a valid
  # Artist. As you add validations to Artist, be sure to
  # adjust the attributes here as well.
  

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArtistsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before :each do
    some_user = FactoryGirl.create(:user)
    sign_in some_user
    @artist = FactoryGirl.create(:artist)
    @invalid_artist = FactoryGirl.build(:invalid_artist)
  end

  describe "GET index" do
    it "assigns all artists as @artists" do
      get :index, {}, valid_session
      assigns(:artists).should eq([@artist])
    end
  end

  describe "GET show" do
    it "assigns the requested artist as @artist" do
      get :show, {:id => @artist.to_param}, valid_session
      assigns(:artist).should eq(@artist)
    end

    it "renders the #show view" do
      get :show, {:id => @artist.to_param}, valid_session
      response.should render_template :show
    end

  end

  describe "GET new" do
    it "assigns a new artist as @artist" do
      get :new, {}, valid_session
      assigns(:artist).should be_a_new(Artist)
    end
  end

  describe "GET edit" do
    it "assigns the requested artist as @artist" do
      get :edit, {:id => @artist.to_param}, valid_session
      assigns(:artist).should eq(@artist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Artist" do
        expect {
          post :create, {:artist => FactoryGirl.attributes_for(:artist)}, valid_session
        }.to change(Artist, :count).by(1)
      end

      it "assigns a newly created artist as @artist" do
        post :create, {:artist => FactoryGirl.attributes_for(:artist)}, valid_session
        assigns(:artist).should be_a(Artist)
        assigns(:artist).should be_persisted
      end

      it "redirects to the created artist" do
        post :create, {:artist => FactoryGirl.attributes_for(:artist)}, valid_session
        response.should redirect_to(Artist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved artist as @artist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Artist.any_instance.stub(:save).and_return(false)
        post :create, {:artist => FactoryGirl.attributes_for(:invalid_artist)}, valid_session
        assigns(:artist).should be_a_new(Artist)
      end

      it "does not save the new artist" do
        expect{
          post :create, {:artist => FactoryGirl.attributes_for(:invalid_artist)}
        }.to_not change(Artist, :count)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Artist.any_instance.stub(:save).and_return(false)
        post :create, {:artist => FactoryGirl.attributes_for(:invalid_artist)}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do

      it "locates the requested artist" do
        put :update, {id: @artist, artist: FactoryGirl.attributes_for(:artist)}, valid_session
        assigns(:artist).should eq(@artist)
      end

      it "updates the requested artist" do
        # Assuming there are no other artists in the database, this
        # specifies that the Artist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Artist.any_instance.should_receive(:update).with({ "name" => "Test_change", "nationality" => "USA" })
        put :update, {:id => @artist.to_param, 
          :artist => FactoryGirl.attributes_for(:artist, name: 'Test_change')}, valid_session
      end

      it "changes the artist's attributes" do
        put :update, {:id => @artist.to_param, 
          :artist => FactoryGirl.attributes_for(:artist, name: 'Test_change')}, valid_session
        @artist.reload
        @artist.name.should eq('Test_change')
      end

      it "assigns the requested artist as @artist" do
        #put :update, {:id => @artist.to_param, :artist => valid_attributes}, valid_session
        put :update, {:id => @artist.to_param, :artist => FactoryGirl.attributes_for(:artist)}, valid_session
        assigns(:artist).should eq(@artist)
      end

      it "redirects to the artist" do
        put :update, {:id => @artist.to_param, :artist => FactoryGirl.attributes_for(:artist)}, valid_session
        response.should redirect_to(@artist)
      end
    end

    describe "with invalid params" do

      it "locates the requested artist" do
        put :update, {id: @artist, artist: FactoryGirl.attributes_for(:invalid_artist)}, valid_session
        assigns(:artist).should eq(@artist)
      end

      it "assigns the artist as @artist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Artist.any_instance.stub(:save).and_return(false)
        put :update, {:id => @artist.to_param, :artist => FactoryGirl.attributes_for(:invalid_artist)}, valid_session
        assigns(:artist).should eq(@artist)
      end

      it "does not change the artist's attributes" do
        put :update, {:id => @artist.to_param, :artist => FactoryGirl.attributes_for(:invalid_artist)}, valid_session
        @artist.reload
        @nationality.should_not eq("Invalid")
      end
    
      it "re-renders the 'edit' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Artist.any_instance.stub(:save).and_return(false)
        put :update, {:id => @artist.to_param, :artist => FactoryGirl.attributes_for(:invalid_artist)}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested artist" do
      expect {
        delete :destroy, {:id => @artist.to_param}, valid_session
      }.to change(Artist, :count).by(-1)
    end

    it "redirects to the artists list" do
      delete :destroy, {:id => @artist.to_param}, valid_session
      response.should redirect_to(artists_url)
    end
  end

end
